
services:
  web:
    build: .
    container_name: inventory_management-web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    #envionment:
     # - PG_USER=postgres
      # - PG_PASSWORD=postgres
      # - PG_DB=inventory_db
      # - PG_HOST=db
      # - PG_PORT=5432
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgis/postgis:latest
    container_name: inventory_management-db
    environment:
      POSTGRES_DB: inventory_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:
